on: release

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - run: python generate-tex.py > tex/eclab-beamer.tex
    - uses: xu-cheng/latex-action@v2
      with:
        working_directory: tex
        root_file: eclab-beamer.tex
        latexmk_use_xelatex: true
    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          tex/eclab-beamer.tex
          tex/eclab-beamer.pdf
